# Basic build settings
[build]
  command = "npm install && npm run build"
  publish = "out"

# Environment variables
[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
  NPM_CONFIG_PRODUCTION = "false"
  NEXT_PUBLIC_SITE_URL = "https://onryl-entrance-clone.netlify.app"

# Use Netlify Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
